id: A8554C956
title: Supplement to the Longchen Nyingtik Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.473003
  last_modified_at: 2022-02-28 23:53:02.473006
