id: A8554C956
title: 'The Radiant Treasure of Blessings: A Guru Yoga of the Great Vajradhara Ngawang
  Samten Lodrö'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.545580
  last_modified_at: 2022-02-28 23:53:02.545582
