id: A8554C956
title: Guru Yoga of Jetsün Shepa Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.380140
  last_modified_at: 2022-02-28 23:53:02.380142
