id: A8554C956
title: Prayer to Jamyang Khyentse Wangpo and Jamyang Khyentse Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.433091
  last_modified_at: 2022-02-28 23:53:02.433093
