id: A8554C956
title: A Brief Method for Reciting Samantabhadra's Prayer of Good Actions
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.250855
  last_modified_at: 2022-02-28 23:53:02.250864
