id: A8554C956
title: Aspiration for the Spread of the Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.319500
  last_modified_at: 2022-02-28 23:53:02.319503
