id: A8554C956
title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling the
  Guru from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.357822
  last_modified_at: 2022-02-28 23:53:02.357825
