id: A8554C956
title: Prayer Written for Lama Chödrak
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.411785
  last_modified_at: 2022-02-28 23:53:02.411788
