id: A8554C956
title: Brief Amitābha Sleeping Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.334341
  last_modified_at: 2022-02-28 23:53:02.334344
