id: A8554C956
title: Prayer on the Occasion of the Reading Transmission for the Omniscient King
  of Dharma's Thirteen-Volume Collected Writings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.427004
  last_modified_at: 2022-02-28 23:53:02.427007
