id: A8554C956
title: Turning Back the Misfortunes of the Age of Degeneration
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.590016
  last_modified_at: 2022-02-28 23:53:02.590019
