id: A8554C956
title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the Supreme
  Tulku of Vajradhara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.598552
  last_modified_at: 2022-02-28 23:53:02.598555
