id: A8554C956
title: In Praise of Yangleshö in Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.390048
  last_modified_at: 2022-02-28 23:53:02.390051
