id: A8554C956
title: A Yearning Plea to the Precious Guru
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.308003
  last_modified_at: 2022-02-28 23:53:02.308006
