id: A8554C956
title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.409578
  last_modified_at: 2022-02-28 23:53:02.409581
