id: A8554C956
title: 'The Purifier of Ethical Discipline: An Aspirational Praise to Vajradhara Kunga
  Zangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.542358
  last_modified_at: 2022-02-28 23:53:02.542361
