id: A8554C956
title: 'Blazing Splendour of Good Fortune: A Prayer for the Spread of the Teachings
  of the Katok Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.332999
  last_modified_at: 2022-02-28 23:53:02.333002
