id: A8554C956
title: Prayer to the Supreme Deities
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.454209
  last_modified_at: 2022-02-28 23:53:02.454212
