id: A8554C956
title: Extremely Secret Unelaborate Daily SÄdhana for the Heart Practice of the Great
  Demon-Slayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.364318
  last_modified_at: 2022-02-28 23:53:02.364321
