id: A8554C956
title: Extemporary Practice of Longevity for Oneself or Others
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.363281
  last_modified_at: 2022-02-28 23:53:02.363284
