id: A8554C956
title: Brief Vajrasattva Visualisation and Mantra Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.337580
  last_modified_at: 2022-02-28 23:53:02.337583
