id: A8554C956
title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
  Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.576512
  last_modified_at: 2022-02-28 23:53:02.576516
