id: A8554C956
title: Aspiration Written on the Occasion of Princess Sangdé’s Passing in Sikkim
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.313999
  last_modified_at: 2022-02-28 23:53:02.314002
