id: A8554C956
title: A Brief Visualization and Recitation of the Great Mother Praj침캐p캐ramit캐
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.252286
  last_modified_at: 2022-02-28 23:53:02.252289
