id: A8554C956
title: A Prayer to the Three Stūpas of Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.297884
  last_modified_at: 2022-02-28 23:53:02.297887
