id: A8554C956
title: 'The Gathering of Blessings: A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.513483
  last_modified_at: 2022-02-28 23:53:02.513486
