id: A8554C956
title: A Song Requested by the Buddhist Monk Jamyang Yönten Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.302424
  last_modified_at: 2022-02-28 23:53:02.302427
