id: A8554C956
title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.495989
  last_modified_at: 2022-02-28 23:53:02.495992
