id: A8554C956
title: A Prayer to Orgyen Dorje Chang
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.291774
  last_modified_at: 2022-02-28 23:53:02.291776
