id: A8554C956
title: 'Waves in A Sea of Devotion: A Prayer to the Garland of Zurmang Trungpa Rinpoche
  Incarnations'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.595850
  last_modified_at: 2022-02-28 23:53:02.595853
