id: A8554C956
title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness and Wellbeing'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.593022
  last_modified_at: 2022-02-28 23:53:02.593025
