id: A8554C956
title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.494331
  last_modified_at: 2022-02-28 23:53:02.494333
