id: A8554C956
title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long Life
  of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.555061
  last_modified_at: 2022-02-28 23:53:02.555064
