id: A8554C956
title: 'The Beautiful Garland of Uḍumbara Flowers: A Prayer to the Previous Incarnations
  of Jamyang Khyentse Chökyi Lodrö'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.485790
  last_modified_at: 2022-02-28 23:53:02.485794
