id: A8554C956
title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.463789
  last_modified_at: 2022-02-28 23:53:02.463792
