id: A8554C956
title: 'The Revelling Ocean of Blessings: A Prayer to Tsarchen Dorje Chang'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.547191
  last_modified_at: 2022-02-28 23:53:02.547194
