id: A8554C956
title: 'The Tree of Awakening: A Prayer to the Great Abbot Śāntarakṣita'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.584846
  last_modified_at: 2022-02-28 23:53:02.584848
