id: A8554C956
title: 'Devotion that Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.355299
  last_modified_at: 2022-02-28 23:53:02.355302
