id: A8554C956
title: Guru Yoga of Lord Marpa Lotsāwa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.381292
  last_modified_at: 2022-02-28 23:53:02.381295
