id: A8554C956
title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
  the Great Omniscient Jonangpa from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.311430
  last_modified_at: 2022-02-28 23:53:02.311433
