id: A8554C956
title: 'The Sound of the Auspicious Conch: A Prayer for the Long Life of the All-Knowing
  Paṇchen Rinpoche of Tsang'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.552151
  last_modified_at: 2022-02-28 23:53:02.552154
