id: A8554C956
title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.382315
  last_modified_at: 2022-02-28 23:53:02.382318
