id: A8554C956
title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great Tertön
  Dudjom Jigdral Yeshe Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.497503
  last_modified_at: 2022-02-28 23:53:02.497506
