id: A8554C956
title: 'Song of Devotion: A Prayer to Lord Marpa LotsÄwa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.468581
  last_modified_at: 2022-02-28 23:53:02.468584
