id: A8554C956
title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the Supreme
  Tulku of the Mañjughoṣa Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.565921
  last_modified_at: 2022-02-28 23:53:02.565926
