id: A8554C956
title: 'The Fulfilment of All Aims and Wishes: An Aspiration to Request the Safeguarding
  of Happiness in Tibet'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.508473
  last_modified_at: 2022-02-28 23:53:02.508476
