id: A8554C956
title: 'Ḍākinī’s Delight: A Song of the Feast'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.600680
  last_modified_at: 2022-02-28 23:53:02.600683
