id: A8554C956
title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.559852
  last_modified_at: 2022-02-28 23:53:02.559855
