id: A8554C956
title: 'The Liberating Guide: A Prayer to Gyalwa Yangönpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.521109
  last_modified_at: 2022-02-28 23:53:02.521111
