id: A8554C956
title: 'Great Drum of the Devas: A Prayer to the Dharma King Tri Songdetsen'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.371700
  last_modified_at: 2022-02-28 23:53:02.371703
