id: A8554C956
title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
  White and Red Amitāyus'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.489177
  last_modified_at: 2022-02-28 23:53:02.489180
