id: A8554C956
title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.341517
  last_modified_at: 2022-02-28 23:53:02.341520
