id: A8554C956
title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural Transmission
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.452578
  last_modified_at: 2022-02-28 23:53:02.452582
