id: A8554C956
title: 'Gathering Auspiciousness: A Prayer of Aspiration Made in the Presence of the
  Sacred Mahābodhi Temple and its Imagery, Magadha, Land of the Āryas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.369882
  last_modified_at: 2022-02-28 23:53:02.369884
