id: A8554C956
title: Guru Yoga of the Guru MahÄmuni
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.384963
  last_modified_at: 2022-02-28 23:53:02.384966
