id: A8554C956
title: 'Thunderous Melody: In Praise of the Omniscient Gorampa Sonam Senge'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.586245
  last_modified_at: 2022-02-28 23:53:02.586248
