id: A8554C956
title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.342895
  last_modified_at: 2022-02-28 23:53:02.342898
