id: A8554C956
title: 'Padma’s Melodious Song: A Prayer for the Long Life of the Fourth in the Succession
  of Lotus-Tongued Jamchen Tai Situ Incarnations'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.401779
  last_modified_at: 2022-02-28 23:53:02.401782
