id: A8554C956
title: Prayer to Tsarchen Losal Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.446478
  last_modified_at: 2022-02-28 23:53:02.446481
