id: A8554C956
title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.419624
  last_modified_at: 2022-02-28 23:53:02.419627
