id: A8554C956
title: 'The Bright Lamp of the Heart Essence (Nyingtik Saldrön): A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.491628
  last_modified_at: 2022-02-28 23:53:02.491631
