id: A8554C956
title: 'The Torch of Wisdom: A Method of Offering Butter Lamps Based on Ārya Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.578840
  last_modified_at: 2022-02-28 23:53:02.578843
