id: A8554C956
title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the Omniscient
  Buddha''s Teachings'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.550447
  last_modified_at: 2022-02-28 23:53:02.550455
