id: A8554C956
title: 'Sweet Song of Enduring Deathlessness: A Prayer for the Long Life of Jamyang
  Khyentse Chökyi Lodrö'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.477689
  last_modified_at: 2022-02-28 23:53:02.477692
