id: A8554C956
title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche, Embodiment
  of All Sources of Refuge'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.553574
  last_modified_at: 2022-02-28 23:53:02.553577
