id: A8554C956
title: Lamenting Prayer to Jamyang Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.392831
  last_modified_at: 2022-02-28 23:53:02.392833
