id: A8554C956
title: Prayer to Khenpo Ngawang Palzang
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.438035
  last_modified_at: 2022-02-28 23:53:02.438038
