id: A8554C956
title: 'The Sweet Song of Māra''s Defeat: A Prayer for the Long Life of the Great
  Tertön and Vidyādhara Lerab Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.556631
  last_modified_at: 2022-02-28 23:53:02.556633
