id: A8554C956
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.415559
  last_modified_at: 2022-02-28 23:53:02.415562
