id: A8554C956
title: How to Recite the Dhāraṇīsūtra of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.386616
  last_modified_at: 2022-02-28 23:53:02.386619
