id: A8554C956
title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.564394
  last_modified_at: 2022-02-28 23:53:02.564397
