id: A8554C956
title: A Prayer of Aspiration for the Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.260940
  last_modified_at: 2022-02-28 23:53:02.260944
