id: A8554C956
title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages of
  the Path Combined with Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.569744
  last_modified_at: 2022-02-28 23:53:02.569747
