id: A8554C956
title: Guru Sādhana of the Omniscient Dolpopa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.377775
  last_modified_at: 2022-02-28 23:53:02.377778
