id: A8554C956
title: Prayer to Yeshe Tsogyal
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.448423
  last_modified_at: 2022-02-28 23:53:02.448426
