id: A8554C956
title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.393908
  last_modified_at: 2022-02-28 23:53:02.393911
