id: A8554C956
title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.353422
  last_modified_at: 2022-02-28 23:53:02.353425
