id: A8554C956
title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.395544
  last_modified_at: 2022-02-28 23:53:02.395546
