id: A8554C956
title: Guru Sādhana of Glorious Dharmakīrti
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.376646
  last_modified_at: 2022-02-28 23:53:02.376649
