id: A8554C956
title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer to Mahākāla
  and Consort'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.480051
  last_modified_at: 2022-02-28 23:53:02.480054
