id: A8554C956
title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled Kindness,
  Drodül Pawo Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.483221
  last_modified_at: 2022-02-28 23:53:02.483224
