id: A8554C956
title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord Atiśa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.330846
  last_modified_at: 2022-02-28 23:53:02.330849
