id: A8554C956
title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
  of the Eight Great Chariots of the Practice Lineage'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.310169
  last_modified_at: 2022-02-28 23:53:02.310172
