id: A8554C956
title: Prayer Composed for Yakzé Tsewang Gyurme
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.404197
  last_modified_at: 2022-02-28 23:53:02.404200
