id: A8554C956
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.439136
  last_modified_at: 2022-02-28 23:53:02.439138
