id: A8554C956
title: 'The Tamboura of Devotion: A Prayer to Götsang Gönpo Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.573972
  last_modified_at: 2022-02-28 23:53:02.573975
