id: A8554C956
title: A Song of Innermost Praise to Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.303924
  last_modified_at: 2022-02-28 23:53:02.303927
