id: A8554C956
title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to the Glorious
  Guru Mah캐k캐la Pa침jaran캐tha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.510227
  last_modified_at: 2022-02-28 23:53:02.510230
