id: A8554C956
title: Brief Turning Back the Summons
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.336522
  last_modified_at: 2022-02-28 23:53:02.336525
