id: A8554C956
title: Prayer to the Supremely Learned Holders of the Glorious Sakya Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.455833
  last_modified_at: 2022-02-28 23:53:02.455836
