id: A8554C956
title: Aspiration to Follow the Gurus of the Ngor Tradition
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.325055
  last_modified_at: 2022-02-28 23:53:02.325059
