id: A8554C956
title: 'Ripples on the Ganges: In Praise of the Goddess Sarasvatī'
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.459982
  last_modified_at: 2022-02-28 23:53:02.459985
