id: A8554C956
title: Prayer to Bhagavān Mañjughoṣa
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.428285
  last_modified_at: 2022-02-28 23:53:02.428287
