id: A8554C956
title: 'Self-Arising Wisdom: Songtsen Gampo Guru Sādhana'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.462640
  last_modified_at: 2022-02-28 23:53:02.462642
