id: A8554C956
title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual for
  The Vajrakīla Root Tantra Section'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.481526
  last_modified_at: 2022-02-28 23:53:02.481528
