id: A8554C956
title: Short Prayer to Atiśa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.464955
  last_modified_at: 2022-02-28 23:53:02.464957
