id: A8554C956
title: 'The Treasure of Wisdom Illumination: A Prayer to the Omniscient Sun of the
  Teachings Sonam Senge'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.581069
  last_modified_at: 2022-02-28 23:53:02.581073
