id: A8554C956
title: Petitionary Offering to Norbu Dradül Tsal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.402826
  last_modified_at: 2022-02-28 23:53:02.402828
