id: A8554C956
title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.512256
  last_modified_at: 2022-02-28 23:53:02.512258
