id: A8554C956
title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
  Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace of
  the Dharmadhātu'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.567653
  last_modified_at: 2022-02-28 23:53:02.567656
