id: A8554C956
title: Prayer of the Wisdom Mind
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.425659
  last_modified_at: 2022-02-28 23:53:02.425662
