id: A8554C956
title: Prayer for the Long Life of the Glorious Sakyapa Father and Son
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.418264
  last_modified_at: 2022-02-28 23:53:02.418267
