id: A8554C956
title: Aspiration for Rebirth in Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.315391
  last_modified_at: 2022-02-28 23:53:02.315393
