id: A8554C956
title: A Prayer to the Svayambhū Stūpa in Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.296521
  last_modified_at: 2022-02-28 23:53:02.296524
