id: A8554C956
title: In Praise of Jigme Lingpa’s Pre-Eminence
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.388820
  last_modified_at: 2022-02-28 23:53:02.388823
