id: A8554C956
title: Verses of Auspiciousness
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.591554
  last_modified_at: 2022-02-28 23:53:02.591557
