id: A8554C956
title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of Abhirati'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.400063
  last_modified_at: 2022-02-28 23:53:02.400066
