id: A8554C956
title: 'Beautiful String of Jewels: A Heart Advice'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.329580
  last_modified_at: 2022-02-28 23:53:02.329583
