id: A8554C956
title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen Chokgyur
  Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.500013
  last_modified_at: 2022-02-28 23:53:02.500016
