id: A8554C956
title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice to the
  Tigress
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:53:02.421326
  last_modified_at: 2022-02-28 23:53:02.421330
